name: Ensure Java compiles
on: push

jobs:
  Project-Compiles:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: DanySK/action-checkout@0.2.28
        - name: Ensure project compiles
          run: |
            chmod +x ./gradlew
            ./gradlew compileJava